name: Data Point
description: Enter data point.
labels: ["data"]
title: "[data]: "
body:
  - type: textarea
    id: data-information
    attributes:
      label: data information
      description: Add information about the data.
      placeholder: Russia has 50,000 cubic feet of natural gas reserves/
    validations:
      required: true
  - type: textarea
    id: data-ref
    attributes:
      label: data ref
      description: Add any references to already existing issue items
      placeholder: "#155"
    validations:
      required: false
